version: "3.9"

services:
  # microservice1-bands:
  #   build:
  #     context: ./db/bands # Path to the Microservice 1 directory
  #   container_name: bands-db
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: bands_db
  #   ports:
  #     - "3307:3306" # Exposing on a different port to avoid conflict
  #   volumes:
  #     - bands_data:/var/lib/mysql # Persist data
  #   networks:
  #     - music_platform_network

  albums:
    build:
      context: ./db/albums # Path to the Microservice 2 directory
    container_name: albums-db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      retries: 5
      start_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: albums_db
    volumes:
      - albums_data:/var/lib/mysql # Persist data
    networks:
      - backnet
    expose:
      - 3306
      - 33060
    # networks:
    #   - music_platform_network

  api:
    build:
      context: ./backend
      target: builder
    container_name: fastapi-application
    environment:
      PORT: 8000
    ports:
      - "8000:8000"
    networks:
      - backnet
    depends_on:
      albums:
        condition: service_healthy
    restart: "no"

volumes:
  bands_data:
  albums_data:

networks:
  backnet:
  frontnet:
