version: "3.9"

services:
  api:
    build:
      context: ./backend
      target: builder
    container_name: fastapi-application
    image: fastapi-application
    environment:
      PORT: 8000
      ALBUM_USERNAME: ${ALBUM_USERNAME}
      ALBUM_PASSWORD: ${ALBUM_PASSWORD}
      ALBUM_HOST: ${ALBUM_HOST}
      ALBUM_PORT: ${ALBUM_PORT}
      ALBUM_DATABASE: ${ALBUM_DATABASE}
      BANDS_USERNAME: ${BANDS_USERNAME}
      BANDS_PASSWORD: ${BANDS_PASSWORD}
      BANDS_HOST: ${BANDS_HOST}
      BANDS_PORT: ${BANDS_PORT}
      BANDS_DATABASE: ${BANDS_DATABASE}
    ports:
      - "8000:8000"
    restart: on-failure
