name: CD Pipeline
on:
  workflow_run:
    workflows: ["CI Build"]
    types:
      - completed
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Pull Latest Docker Images
        working-directory: Code
        run: sudo docker compose pull

      - name: Stop and Remove Existing Services
        working-directory: Code
        run: sudo docker compose down || true

      - name: Start Services
        working-directory: Code
        run: sudo docker compose up -d
