name: CD Pipeline
on:
  workflow_run:
    workflows: ["CI Build"]
    types:
      - completed
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: sudo docker pull cast0rm/fastapi-application:latest

      - name: Delete Old docker container
        run: sudo docker rm -f fastapi-application || true

      - name: Run Docker Container
        env:
          ALBUM_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          ALBUM_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          ALBUM_HOST: ${{ secrets.ALBUM_DATABASE_URL }}
          ALBUM_PORT: 3306
          ALBUM_DATABASE: ${{ secrets.ALBUM_DATABASE_NAME }}
          BANDS_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          BANDS_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          BANDS_HOST: ${{ secrets.BANDS_DATABASE_URL }}
          BANDS_PORT: 3306
          BANDS_DATABASE: ${{ secrets.BANDS_DATABASE_NAME }}
        run: >
          sudo docker run -d 
          -p 8000:8000 
          --name fastapi-application 
          -e ALBUM_USERNAME 
          -e ALBUM_PASSWORD 
          -e ALBUM_HOST 
          -e ALBUM_PORT 
          -e ALBUM_DATABASE 
          -e BANDS_USERNAME 
          -e BANDS_PASSWORD 
          -e BANDS_HOST 
          -e BANDS_PORT 
          -e BANDS_DATABASE 
          cast0rm/fastapi-application:latest
